/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;
import com.jxgm.config.AppConfig;
import javax.sql.DataSource;

import org.springframework.context.support.GenericApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) throws IOException {

        GenericApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfig.class);
        // DataSource dataSource = ctx.getBean("dataSource", DataSource.class);
        
        ProvinceService pservice =ctx.getBean("provinceService", ProvinceService.class);
        List<Province> provinces = pservice.findAllWithCities();

        List<Province> provincesAll = pservice.findAll();

        for (Province p: provincesAll) {
            System.out.println(p);
            System.out.println(p.getCities());
        }
    }
}
