/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;
import com.jxgm.config.DbConfig;
import javax.sql.DataSource;

import org.springframework.context.support.GenericApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) throws IOException {

        GenericApplicationContext ctx = new AnnotationConfigApplicationContext(DbConfig.class);
        DataSource dataSource = ctx.getBean("dataSource", DataSource.class);
        
        ProvinceService pservice = new ProvinceService();
        pservice.setDataSource(dataSource);
        List<Province> provinces = pservice.findAllWithCities();

        for (Province p: provinces) {
            System.out.println(p);
            System.out.println(p.getCities());
        }
    }
}
