/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jxgm.dao.*;
import com.jxgm.entities.*;

import java.util.List;

public class AppTest {
    @Test public void testFindAll() {
        ProvDao provDao = new PlainProvDao();

         try {
            List<Province> p = provDao.findAll();
            assertEquals(p.size(), 34);
            
        } catch(Exception e) {
		}
    }
}
