/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.util.List;

import org.junit.Test;
import static org.junit.Assert.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;


public class AppTest {
    @Test public void testFindAll() {
        ProvDao provDao = new PlainProvDao();

         try {
            List<Province> p = provDao.findAll();
            assertEquals(p.size(), 34);
            
        } catch(Exception e) {
		}
    }

    @Test public void testAll() {
        IProvinceService pservice = new ProvinceService();

         try {
            List<Province> provinces = pservice.findAll();
            
            Province x = null;
            for (Province p: provinces) {
                if (p.getId().equals("16")) {
                    x = p;
                    break;
                }
            }
            assertEquals(x.getCities().size(), 11);

        } catch(Exception e) {
		}
    }
}
