/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import org.springframework.beans.factory.annotation.Autowired;

import com.jxgm.service.*;
import com.jxgm.entities.*;

import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Component
public class MyRunner implements CommandLineRunner {

    private static final Logger logger = LoggerFactory.getLogger(MyRunner.class);

    @Autowired
    private ProvService provService;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("okkkkkkkkkkkkkkkkkkkkk");
        Optional<Province> p = provService.findById(new Long(16));
        if (p.isPresent()) {
            Province x = p.get();
            logger.info("{}", x);
        }
    }
}