/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;
import com.jxgm.DBConnection.DB;

import org.springframework.jdbc.datasource.SimpleDriverDataSource;

public class App {

    public static void main(String[] args) throws IOException {

        SimpleDriverDataSource ds = DB.getDataSource();
        ProvinceService pservice = new ProvinceService();
        pservice.setDataSource(ds);
        List<Province> provinces = pservice.findAllWithCities();

        for (Province p: provinces) {
            System.out.println(p);
            System.out.println(p.getCities());
        }
    }
}
