/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;

public class App {

    public static void main(String[] args) throws IOException {

        IProvinceService pservice = new ProvinceService();
        List<Province> provinces = pservice.findAll();

        for (Province p: provinces) {
            System.out.println(p);
            System.out.println(p.getCities());
        }
    }
}
