/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;

public class App {
    private static ProvDao provDao = new PlainProvDao();
    private static CityDao cityDao = new PlainCityDao();

    public static void main(String[] args) throws IOException {

        IProvinceService pservice = new ProvinceService();

         try {
            List<Province> provinces = pservice.findAll();
            
            // Province x = null;
            for (Province p: provinces) {

                System.out.println(p);
                System.out.println(p.getCities());
                // if (p.getId().equals("16")) {
                //     x = p;
                //     break;
                // }
            }
            

        } catch(Exception e) {
		}
    }
}
