/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;

public class App {
    private static ProvDao provDao = new PlainProvDao();
    private static CityDao cityDao = new PlainCityDao();

    public static void main(String[] args) throws IOException {

        IProvinceService pservice = new ProvinceService();

         try {
            long startTime = System.currentTimeMillis();

            List<Province> provinces = pservice.findAll();

            for (Province p: provinces) {

                System.out.println(p);
                System.out.println(p.getCities());
            }

            long endTime = System.currentTimeMillis();
            System.out.println("程序运行时间：" + (endTime - startTime)/1000 + "s");
            

            long startTime1 = System.currentTimeMillis();
            List<Province> provinces2 = pservice.findAllWithCities();
            
            for (Province p: provinces2) {

                System.out.println(p);
                System.out.println(p.getCities());
            }

            long endTime1 = System.currentTimeMillis();
            System.out.println("程序运行时间：" + (endTime1 - startTime1)/1000 + "s");

        } catch(Exception e) {
		}
    }
}
