/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;
import com.jxgm.service.*;
import com.jxgm.config.AppConfig;
import javax.sql.DataSource;

import org.springframework.context.support.GenericApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;

@Component
public class App {

    public static void main(String[] args) throws IOException {

        GenericApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfig.class);
        // DataSource dataSource = ctx.getBean("dataSource", DataSource.class);
        
        // ProvinceService pservice = ctx.getBean("namedService", ProvinceService.class);
        App app = ctx.getBean(App.class);
        app.run();
    }

    @Autowired
    private ProvinceService pservice;
    
    private void run() {

        List<Province> provinces = pservice.findAllWithCities();

        for (Province p: provinces) {
            System.out.println(p);
            System.out.println(p.getCities());
        }

    }
}
