/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;
import java.sql.*;

import org.springframework.context.support.GenericApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.jxgm.config.AppConfig;
import com.jxgm.service.ProvService;
import com.jxgm.service.ProvServiceImpl;
import com.jxgm.service.IJProvinceService;
import com.jxgm.service.JProvinceService;
import com.jxgm.entities.Province;

public class App {

    public static void main(String[] args) throws IOException {

        GenericApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfig.class);
        ProvService provService = ctx.getBean("springJpaProvinceService", ProvService.class);

        Optional<Province> p = provService.findById(new Long(16));
        if (p.isPresent()) {
            Province x = p.get();
            System.out.println(x);
            System.out.println(x.getCities());
        }

        System.out.println(provService.findAll());

        IJProvinceService pservice = ctx.getBean("namedService", JProvinceService.class);
        List<Province> provinces = pservice.findAllWithCities();

        System.out.println(provinces);

    }
}
